"""
================================================================================
Level 5: Expert Python
Lesson 1: CPython Virtual Machine & Bytecode Disassembly
================================================================================
📝 Quick Exercise Prompt:

Disassemble a list comprehension `[x*2 for x in nums]` and compare its generated bytecode against a standard `for` loop calling `list.append()`. Notice why list comprehensions execute faster at the C level.
================================================================================
"""

# Write your solution below:

